name: couchdb_dart
description: A small simple package to make it easier to use a CouchDB server
version: 1.0.0
repository: https://github.com/TheKingDave/couchdb_dart

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
