version: '3.8'

services:
  couchdb_dart:
    image: couchdb:latest
    container_name: couchdb
    ports:
      - '5984:5984'
    volumes:
      - ./data:/opt/couchdb/data/
      - ./config:/opt/couchdb/etc/local.d/
